// Generated by https://quicktype.io

export interface ProductInterface {
  _id: string;
  id: string;
  name: string;
  price: number;
  salePrice: number | null;
  collection: string[];
  category: string[];
  tags: string[];
  images: string[];
  sizes?: string[];
  color: string[];
  specifications: string[];
  reviews: string[];
  link: string;
  totalStars: number | null;
  description: null | string;
}
